site_name: Nicolas Richard
site_url: https://nicolas-richard.github.io

theme:
  name: material
  palette:
    scheme: default
    primary: white
    accent: black
  font:
    text: false
    code: false
  features:
    - navigation.instant

extra:
  generator: false

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - blog:
      blog_dir: blog

nav:
  - Blog: blog/index.md
