site_name: "Nicolas Richard's Engineering Blog"
site_url: https://nicolas-richard.github.io

theme:
  name: material
  palette:
    scheme: default
    primary: indigo

plugins:
  - search
  - blog

nav:
  - Home: index.md
  - Blog: blog/index.md
